//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApplicationConsole.AgencyMossonBookingServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AgencyMossonBookingServiceRef.AgencyBookingWebServiceSoap")]
    public interface AgencyBookingWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name hotelName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doBooking", ReplyAction="*")]
        ClientApplicationConsole.AgencyMossonBookingServiceRef.doBookingResponse doBooking(ClientApplicationConsole.AgencyMossonBookingServiceRef.doBookingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doBooking", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientApplicationConsole.AgencyMossonBookingServiceRef.doBookingResponse> doBookingAsync(ClientApplicationConsole.AgencyMossonBookingServiceRef.doBookingRequest request);
        string doBooking(string hotelName, int roomId, string clientFirstName, string clientLastName, string clientCardInfo);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doBookingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doBooking", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplicationConsole.AgencyMossonBookingServiceRef.doBookingRequestBody Body;
        
        public doBookingRequest() {
        }
        
        public doBookingRequest(ClientApplicationConsole.AgencyMossonBookingServiceRef.doBookingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doBookingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hotelName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int roomId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string clientFirstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string clientLastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string clientCardInfo;
        
        public doBookingRequestBody() {
        }
        
        public doBookingRequestBody(string hotelName, int roomId, string clientFirstName, string clientLastName, string clientCardInfo) {
            this.hotelName = hotelName;
            this.roomId = roomId;
            this.clientFirstName = clientFirstName;
            this.clientLastName = clientLastName;
            this.clientCardInfo = clientCardInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doBookingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doBookingResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientApplicationConsole.AgencyMossonBookingServiceRef.doBookingResponseBody Body;
        
        public doBookingResponse() {
        }
        
        public doBookingResponse(ClientApplicationConsole.AgencyMossonBookingServiceRef.doBookingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doBookingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string doBookingResult;
        
        public doBookingResponseBody() {
        }
        
        public doBookingResponseBody(string doBookingResult) {
            this.doBookingResult = doBookingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AgencyBookingWebServiceSoapChannel : ClientApplicationConsole.AgencyMossonBookingServiceRef.AgencyBookingWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgencyBookingWebServiceSoapClient : System.ServiceModel.ClientBase<ClientApplicationConsole.AgencyMossonBookingServiceRef.AgencyBookingWebServiceSoap>, ClientApplicationConsole.AgencyMossonBookingServiceRef.AgencyBookingWebServiceSoap {
        
        public AgencyBookingWebServiceSoapClient() {
        }
        
        public AgencyBookingWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgencyBookingWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgencyBookingWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgencyBookingWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientApplicationConsole.AgencyMossonBookingServiceRef.doBookingResponse ClientApplicationConsole.AgencyMossonBookingServiceRef.AgencyBookingWebServiceSoap.doBooking(ClientApplicationConsole.AgencyMossonBookingServiceRef.doBookingRequest request) {
            return base.Channel.doBooking(request);
        }
        
        public string doBooking(string hotelName, int roomId, string clientFirstName, string clientLastName, string clientCardInfo) {
            ClientApplicationConsole.AgencyMossonBookingServiceRef.doBookingRequest inValue = new ClientApplicationConsole.AgencyMossonBookingServiceRef.doBookingRequest();
            inValue.Body = new ClientApplicationConsole.AgencyMossonBookingServiceRef.doBookingRequestBody();
            inValue.Body.hotelName = hotelName;
            inValue.Body.roomId = roomId;
            inValue.Body.clientFirstName = clientFirstName;
            inValue.Body.clientLastName = clientLastName;
            inValue.Body.clientCardInfo = clientCardInfo;
            ClientApplicationConsole.AgencyMossonBookingServiceRef.doBookingResponse retVal = ((ClientApplicationConsole.AgencyMossonBookingServiceRef.AgencyBookingWebServiceSoap)(this)).doBooking(inValue);
            return retVal.Body.doBookingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientApplicationConsole.AgencyMossonBookingServiceRef.doBookingResponse> ClientApplicationConsole.AgencyMossonBookingServiceRef.AgencyBookingWebServiceSoap.doBookingAsync(ClientApplicationConsole.AgencyMossonBookingServiceRef.doBookingRequest request) {
            return base.Channel.doBookingAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientApplicationConsole.AgencyMossonBookingServiceRef.doBookingResponse> doBookingAsync(string hotelName, int roomId, string clientFirstName, string clientLastName, string clientCardInfo) {
            ClientApplicationConsole.AgencyMossonBookingServiceRef.doBookingRequest inValue = new ClientApplicationConsole.AgencyMossonBookingServiceRef.doBookingRequest();
            inValue.Body = new ClientApplicationConsole.AgencyMossonBookingServiceRef.doBookingRequestBody();
            inValue.Body.hotelName = hotelName;
            inValue.Body.roomId = roomId;
            inValue.Body.clientFirstName = clientFirstName;
            inValue.Body.clientLastName = clientLastName;
            inValue.Body.clientCardInfo = clientCardInfo;
            return ((ClientApplicationConsole.AgencyMossonBookingServiceRef.AgencyBookingWebServiceSoap)(this)).doBookingAsync(inValue);
        }
    }
}
