//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agency_Mosson.HotelRenarviereServiceRef2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Offer", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Offer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int NumberOfBedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateAvailableField;
        
        private int PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NumberOfBed {
            get {
                return this.NumberOfBedField;
            }
            set {
                if ((this.NumberOfBedField.Equals(value) != true)) {
                    this.NumberOfBedField = value;
                    this.RaisePropertyChanged("NumberOfBed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DateAvailable {
            get {
                return this.DateAvailableField;
            }
            set {
                if ((object.ReferenceEquals(this.DateAvailableField, value) != true)) {
                    this.DateAvailableField = value;
                    this.RaisePropertyChanged("DateAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HotelRenarviereServiceRef2.HotelWebService2Soap")]
    public interface HotelWebService2Soap {
        
        // CODEGEN: Generating message contract since element name _userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doBooking", ReplyAction="*")]
        Agency_Mosson.HotelRenarviereServiceRef2.doBookingResponse doBooking(Agency_Mosson.HotelRenarviereServiceRef2.doBookingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/doBooking", ReplyAction="*")]
        System.Threading.Tasks.Task<Agency_Mosson.HotelRenarviereServiceRef2.doBookingResponse> doBookingAsync(Agency_Mosson.HotelRenarviereServiceRef2.doBookingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doBookingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doBooking", Namespace="http://tempuri.org/", Order=0)]
        public Agency_Mosson.HotelRenarviereServiceRef2.doBookingRequestBody Body;
        
        public doBookingRequest() {
        }
        
        public doBookingRequest(Agency_Mosson.HotelRenarviereServiceRef2.doBookingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doBookingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string _password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int _offer_id;
        
        public doBookingRequestBody() {
        }
        
        public doBookingRequestBody(string _userName, string _password, int _offer_id) {
            this._userName = _userName;
            this._password = _password;
            this._offer_id = _offer_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class doBookingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="doBookingResponse", Namespace="http://tempuri.org/", Order=0)]
        public Agency_Mosson.HotelRenarviereServiceRef2.doBookingResponseBody Body;
        
        public doBookingResponse() {
        }
        
        public doBookingResponse(Agency_Mosson.HotelRenarviereServiceRef2.doBookingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class doBookingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Agency_Mosson.HotelRenarviereServiceRef2.Offer doBookingResult;
        
        public doBookingResponseBody() {
        }
        
        public doBookingResponseBody(Agency_Mosson.HotelRenarviereServiceRef2.Offer doBookingResult) {
            this.doBookingResult = doBookingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HotelWebService2SoapChannel : Agency_Mosson.HotelRenarviereServiceRef2.HotelWebService2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelWebService2SoapClient : System.ServiceModel.ClientBase<Agency_Mosson.HotelRenarviereServiceRef2.HotelWebService2Soap>, Agency_Mosson.HotelRenarviereServiceRef2.HotelWebService2Soap {
        
        public HotelWebService2SoapClient() {
        }
        
        public HotelWebService2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelWebService2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelWebService2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelWebService2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agency_Mosson.HotelRenarviereServiceRef2.doBookingResponse Agency_Mosson.HotelRenarviereServiceRef2.HotelWebService2Soap.doBooking(Agency_Mosson.HotelRenarviereServiceRef2.doBookingRequest request) {
            return base.Channel.doBooking(request);
        }
        
        public Agency_Mosson.HotelRenarviereServiceRef2.Offer doBooking(string _userName, string _password, int _offer_id) {
            Agency_Mosson.HotelRenarviereServiceRef2.doBookingRequest inValue = new Agency_Mosson.HotelRenarviereServiceRef2.doBookingRequest();
            inValue.Body = new Agency_Mosson.HotelRenarviereServiceRef2.doBookingRequestBody();
            inValue.Body._userName = _userName;
            inValue.Body._password = _password;
            inValue.Body._offer_id = _offer_id;
            Agency_Mosson.HotelRenarviereServiceRef2.doBookingResponse retVal = ((Agency_Mosson.HotelRenarviereServiceRef2.HotelWebService2Soap)(this)).doBooking(inValue);
            return retVal.Body.doBookingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agency_Mosson.HotelRenarviereServiceRef2.doBookingResponse> Agency_Mosson.HotelRenarviereServiceRef2.HotelWebService2Soap.doBookingAsync(Agency_Mosson.HotelRenarviereServiceRef2.doBookingRequest request) {
            return base.Channel.doBookingAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agency_Mosson.HotelRenarviereServiceRef2.doBookingResponse> doBookingAsync(string _userName, string _password, int _offer_id) {
            Agency_Mosson.HotelRenarviereServiceRef2.doBookingRequest inValue = new Agency_Mosson.HotelRenarviereServiceRef2.doBookingRequest();
            inValue.Body = new Agency_Mosson.HotelRenarviereServiceRef2.doBookingRequestBody();
            inValue.Body._userName = _userName;
            inValue.Body._password = _password;
            inValue.Body._offer_id = _offer_id;
            return ((Agency_Mosson.HotelRenarviereServiceRef2.HotelWebService2Soap)(this)).doBookingAsync(inValue);
        }
    }
}
